// Mocks generated by Mockito 5.4.4 from annotations
// in ngage/test/services/judging_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i10;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:ngage/models/score.dart' as _i2;
import 'package:ngage/models/scoring_rubric.dart' as _i4;
import 'package:ngage/models/submission.dart' as _i5;
import 'package:ngage/models/team.dart' as _i13;
import 'package:ngage/repositories/score_repository.dart' as _i3;
import 'package:ngage/repositories/scoring_rubric_repository.dart' as _i8;
import 'package:ngage/repositories/submission_repository.dart' as _i9;
import 'package:ngage/repositories/team_repository.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScore_0 extends _i1.SmartFake implements _i2.Score {
  _FakeScore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScoreStatistics_1 extends _i1.SmartFake
    implements _i3.ScoreStatistics {
  _FakeScoreStatistics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScoringRubric_2 extends _i1.SmartFake implements _i4.ScoringRubric {
  _FakeScoringRubric_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubmission_3 extends _i1.SmartFake implements _i5.Submission {
  _FakeSubmission_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScoreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScoreRepository extends _i1.Mock implements _i3.ScoreRepository {
  MockScoreRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Score> create(_i2.Score? score) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [score],
        ),
        returnValue: _i6.Future<_i2.Score>.value(_FakeScore_0(
          this,
          Invocation.method(
            #create,
            [score],
          ),
        )),
      ) as _i6.Future<_i2.Score>);

  @override
  _i6.Future<_i2.Score?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i6.Future<_i2.Score?>.value(),
      ) as _i6.Future<_i2.Score?>);

  @override
  _i6.Future<_i2.Score> update(_i2.Score? score) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [score],
        ),
        returnValue: _i6.Future<_i2.Score>.value(_FakeScore_0(
          this,
          Invocation.method(
            #update,
            [score],
          ),
        )),
      ) as _i6.Future<_i2.Score>);

  @override
  _i6.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Score>> getBySubmissionId(String? submissionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBySubmissionId,
          [submissionId],
        ),
        returnValue: _i6.Future<List<_i2.Score>>.value(<_i2.Score>[]),
      ) as _i6.Future<List<_i2.Score>>);

  @override
  _i6.Future<List<_i2.Score>> getByJudgeId(
    String? judgeId, {
    String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByJudgeId,
          [judgeId],
          {#eventId: eventId},
        ),
        returnValue: _i6.Future<List<_i2.Score>>.value(<_i2.Score>[]),
      ) as _i6.Future<List<_i2.Score>>);

  @override
  _i6.Future<List<_i2.Score>> getByEventId(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByEventId,
          [eventId],
        ),
        returnValue: _i6.Future<List<_i2.Score>>.value(<_i2.Score>[]),
      ) as _i6.Future<List<_i2.Score>>);

  @override
  _i6.Future<_i2.Score?> getBySubmissionAndJudge(
    String? submissionId,
    String? judgeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBySubmissionAndJudge,
          [
            submissionId,
            judgeId,
          ],
        ),
        returnValue: _i6.Future<_i2.Score?>.value(),
      ) as _i6.Future<_i2.Score?>);

  @override
  _i6.Future<Map<String, List<_i2.Score>>> getBySubmissionIds(
          List<String>? submissionIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBySubmissionIds,
          [submissionIds],
        ),
        returnValue: _i6.Future<Map<String, List<_i2.Score>>>.value(
            <String, List<_i2.Score>>{}),
      ) as _i6.Future<Map<String, List<_i2.Score>>>);

  @override
  _i6.Stream<List<_i2.Score>> streamBySubmissionId(String? submissionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamBySubmissionId,
          [submissionId],
        ),
        returnValue: _i6.Stream<List<_i2.Score>>.empty(),
      ) as _i6.Stream<List<_i2.Score>>);

  @override
  _i6.Stream<_i2.Score?> streamById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #streamById,
          [id],
        ),
        returnValue: _i6.Stream<_i2.Score?>.empty(),
      ) as _i6.Stream<_i2.Score?>);

  @override
  _i6.Future<double?> getAverageScore(String? submissionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageScore,
          [submissionId],
        ),
        returnValue: _i6.Future<double?>.value(),
      ) as _i6.Future<double?>);

  @override
  _i6.Future<_i3.ScoreStatistics> getEventScoreStatistics(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventScoreStatistics,
          [eventId],
        ),
        returnValue:
            _i6.Future<_i3.ScoreStatistics>.value(_FakeScoreStatistics_1(
          this,
          Invocation.method(
            #getEventScoreStatistics,
            [eventId],
          ),
        )),
      ) as _i6.Future<_i3.ScoreStatistics>);

  @override
  _i6.Future<bool> hasJudgeScored(
    String? submissionId,
    String? judgeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasJudgeScored,
          [
            submissionId,
            judgeId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i2.Score>> getIncompleteScores(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIncompleteScores,
          [eventId],
        ),
        returnValue: _i6.Future<List<_i2.Score>>.value(<_i2.Score>[]),
      ) as _i6.Future<List<_i2.Score>>);

  @override
  _i6.Future<void> deleteBySubmissionId(String? submissionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBySubmissionId,
          [submissionId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteByEventId(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #deleteByEventId,
          [eventId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Score>> getScoresPaginated({
    String? eventId,
    String? submissionId,
    String? judgeId,
    _i7.DocumentSnapshot<Object?>? startAfter,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresPaginated,
          [],
          {
            #eventId: eventId,
            #submissionId: submissionId,
            #judgeId: judgeId,
            #startAfter: startAfter,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<List<_i2.Score>>.value(<_i2.Score>[]),
      ) as _i6.Future<List<_i2.Score>>);
}

/// A class which mocks [ScoringRubricRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScoringRubricRepository extends _i1.Mock
    implements _i8.ScoringRubricRepository {
  MockScoringRubricRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ScoringRubric> create(_i4.ScoringRubric? rubric) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [rubric],
        ),
        returnValue: _i6.Future<_i4.ScoringRubric>.value(_FakeScoringRubric_2(
          this,
          Invocation.method(
            #create,
            [rubric],
          ),
        )),
      ) as _i6.Future<_i4.ScoringRubric>);

  @override
  _i6.Future<_i4.ScoringRubric?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i6.Future<_i4.ScoringRubric?>.value(),
      ) as _i6.Future<_i4.ScoringRubric?>);

  @override
  _i6.Future<_i4.ScoringRubric> update(_i4.ScoringRubric? rubric) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [rubric],
        ),
        returnValue: _i6.Future<_i4.ScoringRubric>.value(_FakeScoringRubric_2(
          this,
          Invocation.method(
            #update,
            [rubric],
          ),
        )),
      ) as _i6.Future<_i4.ScoringRubric>);

  @override
  _i6.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.ScoringRubric>> getByEventId(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByEventId,
          [eventId],
        ),
        returnValue:
            _i6.Future<List<_i4.ScoringRubric>>.value(<_i4.ScoringRubric>[]),
      ) as _i6.Future<List<_i4.ScoringRubric>>);

  @override
  _i6.Future<List<_i4.ScoringRubric>> getByGroupId(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByGroupId,
          [groupId],
        ),
        returnValue:
            _i6.Future<List<_i4.ScoringRubric>>.value(<_i4.ScoringRubric>[]),
      ) as _i6.Future<List<_i4.ScoringRubric>>);

  @override
  _i6.Future<List<_i4.ScoringRubric>> getTemplates() => (super.noSuchMethod(
        Invocation.method(
          #getTemplates,
          [],
        ),
        returnValue:
            _i6.Future<List<_i4.ScoringRubric>>.value(<_i4.ScoringRubric>[]),
      ) as _i6.Future<List<_i4.ScoringRubric>>);

  @override
  _i6.Future<List<_i4.ScoringRubric>> getByCreator(String? creatorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCreator,
          [creatorId],
        ),
        returnValue:
            _i6.Future<List<_i4.ScoringRubric>>.value(<_i4.ScoringRubric>[]),
      ) as _i6.Future<List<_i4.ScoringRubric>>);

  @override
  _i6.Future<List<_i4.ScoringRubric>> searchByName(
    String? searchTerm, {
    String? groupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [searchTerm],
          {#groupId: groupId},
        ),
        returnValue:
            _i6.Future<List<_i4.ScoringRubric>>.value(<_i4.ScoringRubric>[]),
      ) as _i6.Future<List<_i4.ScoringRubric>>);

  @override
  _i6.Future<_i4.ScoringRubric> clone(
    String? rubricId, {
    String? newName,
    String? newEventId,
    String? newGroupId,
    bool? isTemplate,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clone,
          [rubricId],
          {
            #newName: newName,
            #newEventId: newEventId,
            #newGroupId: newGroupId,
            #isTemplate: isTemplate,
            #createdBy: createdBy,
          },
        ),
        returnValue: _i6.Future<_i4.ScoringRubric>.value(_FakeScoringRubric_2(
          this,
          Invocation.method(
            #clone,
            [rubricId],
            {
              #newName: newName,
              #newEventId: newEventId,
              #newGroupId: newGroupId,
              #isTemplate: isTemplate,
              #createdBy: createdBy,
            },
          ),
        )),
      ) as _i6.Future<_i4.ScoringRubric>);

  @override
  _i6.Future<_i4.ScoringRubric> createFromTemplate(
    String? templateId, {
    required String? name,
    String? eventId,
    String? groupId,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFromTemplate,
          [templateId],
          {
            #name: name,
            #eventId: eventId,
            #groupId: groupId,
            #createdBy: createdBy,
          },
        ),
        returnValue: _i6.Future<_i4.ScoringRubric>.value(_FakeScoringRubric_2(
          this,
          Invocation.method(
            #createFromTemplate,
            [templateId],
            {
              #name: name,
              #eventId: eventId,
              #groupId: groupId,
              #createdBy: createdBy,
            },
          ),
        )),
      ) as _i6.Future<_i4.ScoringRubric>);

  @override
  _i6.Future<List<_i4.ScoringRubric>> getRubricsPaginated({
    String? eventId,
    String? groupId,
    bool? isTemplate,
    _i7.DocumentSnapshot<Object?>? startAfter,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRubricsPaginated,
          [],
          {
            #eventId: eventId,
            #groupId: groupId,
            #isTemplate: isTemplate,
            #startAfter: startAfter,
            #limit: limit,
          },
        ),
        returnValue:
            _i6.Future<List<_i4.ScoringRubric>>.value(<_i4.ScoringRubric>[]),
      ) as _i6.Future<List<_i4.ScoringRubric>>);

  @override
  _i6.Stream<List<_i4.ScoringRubric>> streamByEventId(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamByEventId,
          [eventId],
        ),
        returnValue: _i6.Stream<List<_i4.ScoringRubric>>.empty(),
      ) as _i6.Stream<List<_i4.ScoringRubric>>);

  @override
  _i6.Stream<_i4.ScoringRubric?> streamById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #streamById,
          [id],
        ),
        returnValue: _i6.Stream<_i4.ScoringRubric?>.empty(),
      ) as _i6.Stream<_i4.ScoringRubric?>);

  @override
  _i6.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> getGroupRubricCount(String? groupId) => (super.noSuchMethod(
        Invocation.method(
          #getGroupRubricCount,
          [groupId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> getTemplateCount() => (super.noSuchMethod(
        Invocation.method(
          #getTemplateCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> deleteByEventId(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #deleteByEventId,
          [eventId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteByGroupId(String? groupId) => (super.noSuchMethod(
        Invocation.method(
          #deleteByGroupId,
          [groupId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> validateRubric(_i4.ScoringRubric? rubric) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateRubric,
          [rubric],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [SubmissionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmissionRepository extends _i1.Mock
    implements _i9.SubmissionRepository {
  MockSubmissionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i5.Submission> create(_i5.Submission? submission) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [submission],
        ),
        returnValue: _i6.Future<_i5.Submission>.value(_FakeSubmission_3(
          this,
          Invocation.method(
            #create,
            [submission],
          ),
        )),
      ) as _i6.Future<_i5.Submission>);

  @override
  _i6.Future<_i5.Submission?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i6.Future<_i5.Submission?>.value(),
      ) as _i6.Future<_i5.Submission?>);

  @override
  _i6.Future<_i5.Submission> update(_i5.Submission? submission) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [submission],
        ),
        returnValue: _i6.Future<_i5.Submission>.value(_FakeSubmission_3(
          this,
          Invocation.method(
            #update,
            [submission],
          ),
        )),
      ) as _i6.Future<_i5.Submission>);

  @override
  _i6.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.Submission>> getByEventId(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByEventId,
          [eventId],
        ),
        returnValue: _i6.Future<List<_i5.Submission>>.value(<_i5.Submission>[]),
      ) as _i6.Future<List<_i5.Submission>>);

  @override
  _i6.Future<List<_i5.Submission>> getByTeamId(String? teamId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByTeamId,
          [teamId],
        ),
        returnValue: _i6.Future<List<_i5.Submission>>.value(<_i5.Submission>[]),
      ) as _i6.Future<List<_i5.Submission>>);

  @override
  _i6.Future<List<_i5.Submission>> getByMemberId(String? memberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByMemberId,
          [memberId],
        ),
        returnValue: _i6.Future<List<_i5.Submission>>.value(<_i5.Submission>[]),
      ) as _i6.Future<List<_i5.Submission>>);

  @override
  _i6.Future<String> uploadFile(
    String? submissionId,
    _i10.File? file,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            submissionId,
            file,
            fileName,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #uploadFile,
            [
              submissionId,
              file,
              fileName,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<String>> uploadFiles(
    String? submissionId,
    List<_i10.File>? files,
    List<String>? fileNames,
    void Function(double)? onProgress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFiles,
          [
            submissionId,
            files,
            fileNames,
            onProgress,
          ],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<void> deleteFile(
    String? submissionId,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [
            submissionId,
            fileName,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i5.Submission>> streamByEventId(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamByEventId,
          [eventId],
        ),
        returnValue: _i6.Stream<List<_i5.Submission>>.empty(),
      ) as _i6.Stream<List<_i5.Submission>>);

  @override
  _i6.Stream<_i5.Submission?> streamById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #streamById,
          [id],
        ),
        returnValue: _i6.Stream<_i5.Submission?>.empty(),
      ) as _i6.Stream<_i5.Submission?>);

  @override
  _i6.Future<List<_i5.Submission>> getSubmissionsPaginated({
    String? eventId,
    String? teamId,
    _i7.DocumentSnapshot<Object?>? startAfter,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubmissionsPaginated,
          [],
          {
            #eventId: eventId,
            #teamId: teamId,
            #startAfter: startAfter,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<List<_i5.Submission>>.value(<_i5.Submission>[]),
      ) as _i6.Future<List<_i5.Submission>>);

  @override
  _i6.Future<bool> hasTeamSubmitted(
    String? eventId,
    String? teamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasTeamSubmitted,
          [
            eventId,
            teamId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> getSubmissionCount(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getSubmissionCount,
          [eventId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i5.Submission>> getDraftSubmissionsByEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDraftSubmissionsByEvent,
          [eventId],
        ),
        returnValue: _i6.Future<List<_i5.Submission>>.value(<_i5.Submission>[]),
      ) as _i6.Future<List<_i5.Submission>>);
}

/// A class which mocks [TeamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamRepository extends _i1.Mock implements _i12.TeamRepository {
  MockTeamRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> createTeam(_i13.Team? team) => (super.noSuchMethod(
        Invocation.method(
          #createTeam,
          [team],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i13.Team?> getTeamById(String? teamId) => (super.noSuchMethod(
        Invocation.method(
          #getTeamById,
          [teamId],
        ),
        returnValue: _i6.Future<_i13.Team?>.value(),
      ) as _i6.Future<_i13.Team?>);

  @override
  _i6.Future<void> updateTeam(_i13.Team? team) => (super.noSuchMethod(
        Invocation.method(
          #updateTeam,
          [team],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTeam(String? teamId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTeam,
          [teamId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i13.Team>> getTeamsByGroupId(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamsByGroupId,
          [groupId],
        ),
        returnValue: _i6.Future<List<_i13.Team>>.value(<_i13.Team>[]),
      ) as _i6.Future<List<_i13.Team>>);

  @override
  _i6.Future<List<_i13.Team>> getTeamsByTeamLead(String? teamLeadId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamsByTeamLead,
          [teamLeadId],
        ),
        returnValue: _i6.Future<List<_i13.Team>>.value(<_i13.Team>[]),
      ) as _i6.Future<List<_i13.Team>>);

  @override
  _i6.Future<List<_i13.Team>> getTeamsByMember(String? memberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamsByMember,
          [memberId],
        ),
        returnValue: _i6.Future<List<_i13.Team>>.value(<_i13.Team>[]),
      ) as _i6.Future<List<_i13.Team>>);

  @override
  _i6.Future<List<_i13.Team>> getTeamsByType(
    String? groupId,
    String? teamType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamsByType,
          [
            groupId,
            teamType,
          ],
        ),
        returnValue: _i6.Future<List<_i13.Team>>.value(<_i13.Team>[]),
      ) as _i6.Future<List<_i13.Team>>);

  @override
  _i6.Future<List<_i13.Team>> getTeamsByIds(List<String>? teamIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamsByIds,
          [teamIds],
        ),
        returnValue: _i6.Future<List<_i13.Team>>.value(<_i13.Team>[]),
      ) as _i6.Future<List<_i13.Team>>);

  @override
  _i6.Stream<List<_i13.Team>> streamTeamsByGroupId(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamTeamsByGroupId,
          [groupId],
        ),
        returnValue: _i6.Stream<List<_i13.Team>>.empty(),
      ) as _i6.Stream<List<_i13.Team>>);

  @override
  _i6.Stream<List<_i13.Team>> streamTeamsByMember(String? memberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamTeamsByMember,
          [memberId],
        ),
        returnValue: _i6.Stream<List<_i13.Team>>.empty(),
      ) as _i6.Stream<List<_i13.Team>>);

  @override
  _i6.Stream<_i13.Team?> streamTeamById(String? teamId) => (super.noSuchMethod(
        Invocation.method(
          #streamTeamById,
          [teamId],
        ),
        returnValue: _i6.Stream<_i13.Team?>.empty(),
      ) as _i6.Stream<_i13.Team?>);

  @override
  _i6.Future<int> getTeamCountByGroup(String? groupId) => (super.noSuchMethod(
        Invocation.method(
          #getTeamCountByGroup,
          [groupId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> getActiveTeamCountForMember(String? memberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveTeamCountForMember,
          [memberId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> softDeleteTeam(String? teamId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteTeam,
          [teamId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> reactivateTeam(String? teamId) => (super.noSuchMethod(
        Invocation.method(
          #reactivateTeam,
          [teamId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
