// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkA-6Fau3Z7vHDZ2mzLQ1erk0y4i2Sl9E',
    appId: '1:205876580925:web:7705e5cada56fe969ed054',
    messagingSenderId: '205876580925',
    projectId: 'ngage-team-app',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'ngage-team-app.firebasestorage.app',
    measurementId: 'your-measurement-id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkA-6Fau3Z7vHDZ2mzLQ1erk0y4i2Sl9E',
    appId: '1:205876580925:android:8678dc821cc926b49ed054',
    messagingSenderId: '205876580925',
    projectId: 'ngage-team-app',
    storageBucket: 'ngage-team-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkA-6Fau3Z7vHDZ2mzLQ1erk0y4i2Sl9E',
    appId: '1:205876580925:ios:16cb14f698d8ddab9ed054',
    messagingSenderId: '205876580925',
    projectId: 'ngage-team-app',
    storageBucket: 'ngage-team-app.firebasestorage.app',
    iosBundleId: 'app.ngage.team',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkA-6Fau3Z7vHDZ2mzLQ1erk0y4i2Sl9E',
    appId: 'your-macos-app-id',
    messagingSenderId: '205876580925',
    projectId: 'ngage-team-app',
    storageBucket: 'ngage-team-app.firebasestorage.app',
    iosBundleId: 'app.ngage.team',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkA-6Fau3Z7vHDZ2mzLQ1erk0y4i2Sl9E',
    appId: 'your-windows-app-id',
    messagingSenderId: '205876580925',
    projectId: 'ngage-team-app',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'ngage-team-app.firebasestorage.app',
    measurementId: 'your-measurement-id',
  );
}